import { Geist, Geist_Mono } from "next/font/google";
import "./component/globals.css";
import SessionProviderWrapper from "./SessionProviderWrapper";
import { ShopProvider } from "./context/ShopContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        <SessionProviderWrapper>
          <ShopProvider>{children}</ShopProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
